# Sample NZB Touch Configuration

# Usenet providers configuration
download_providers:
  - host: 'news.example.com'
    port: 563
    username: 'your_username'
    password: 'your_password'
    ssl: true
    max_connections: 10
    max_connection_idle_time_in_seconds: 2400

  - host: 'news2.example.com'
    port: 119
    username: 'another_username'
    password: 'another_password'
    ssl: false
    max_connections: 10
    max_connection_idle_time_in_seconds: 2400

# Scanner configuration for directory watching
scanner:
  enabled: true # Enable directory scanning
  watch_directories: # List of directories to scan for NZB files
    - '/path/to/nzb/downloads'
    - '/path/to/another/directory'
  scan_interval: '60m' # Scan interval (60 minutes)
  max_files_per_day: 100 # Maximum number of files to process per day
  concurrent_jobs: 3 # Number of concurrent processing jobs
  database_path: 'queue.db' # SQLite database file for persistent queue
  reprocess_interval: '7d' # Reprocess items after 7 days (set to "0" to disable)
  failed_directory: '/path/to/failed/nzbs' # Directory where failed NZBs are moved to (preserves folder structure)
